# Generated by Django 2.2.3 on 2019-10-18 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20191018_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='NIK',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='NIP',
        ),
    ]
