# Generated by Django 2.2.3 on 2019-10-18 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20191018_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='NIK',
            field=models.CharField(default=True, max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='NIP',
            field=models.CharField(blank=True, default=True, max_length=255),
        ),
    ]
