# Generated by Django 2.2.3 on 2019-10-18 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20191018_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='NIK',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='NIP',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
