# Generated by Django 2.2.6 on 2019-11-25 21:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alamat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alamat', models.CharField(choices=[('Pilih Alamat', '------'), ('Kalimantan', 'kalimantan'), ('Gajah Mada', 'gajah_mada'), ('Jawa', 'jawa'), ('Sumatra', 'sumatra'), ('Karimata', 'karimata'), ('Semeru', 'semeru'), ('Bangka', 'bangka'), ('Halmahera', 'halmahera')], default='Pilih Alamat', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori', models.CharField(choices=[('Jalan', 'jalan'), ('Jembatan', 'jembatan'), ('Lampu Jalan', 'lampu_jalan')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Belum Di Survey', 'belum_di_survey'), ('Sedang Di Survey', 'sedang_di_survey'), ('Telah Di Survey', 'telah_di_survey'), ('Dalam Proses Pengerjaan', 'dalam_proses_pengerjaan'), ('Telah Di Perbaiki', 'telah_di_perbaiki')], default='Belum Di Survey', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WaktuPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waktu_post', models.DateTimeField(auto_now_add=True)),
                ('waktu_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('isi', models.TextField()),
                ('waktu_update', models.DateTimeField(auto_now=True)),
                ('foto', models.ImageField(blank=True, default='blank.jpg', null=True, upload_to='pengaduan')),
                ('WaktuPost', models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='blog.WaktuPost')),
                ('alamat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Alamat')),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Kategori')),
                ('penulis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('status_id', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='blog.Status')),
            ],
        ),
    ]
