# Generated by Django 2.2.6 on 2019-11-25 21:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='WaktuPost',
        ),
        migrations.AddField(
            model_name='post',
            name='waktu_post',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
