# Generated by Django 2.2.3 on 2019-10-20 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20191012_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='alamat',
            field=models.CharField(choices=[('Pilih Alamat', '------'), ('Kalimantan', 'kalimantan'), ('Gajah Mada', 'gajah_mada'), ('Jawa', 'jawa'), ('Sumatra', 'sumatra'), ('Karimata', 'karimata'), ('Semeru', 'semeru'), ('Bangka', 'bangka'), ('Halmahera', 'halmahera')], default='Pilih Alamat', max_length=255),
        ),
    ]
