# Generated by Django 2.2.6 on 2019-11-25 21:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Surveyor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('waktu_post', models.DateTimeField(auto_now=True)),
                ('kerusakan', models.CharField(choices=[('Parah', 'parah'), ('Sedang', 'sedang'), ('Ringan', 'ringan')], default='Ringan', max_length=255)),
                ('lalu_lintas', models.CharField(choices=[('Padat', 'padat'), ('Sedang', 'sedang'), ('Sepi', 'sepi')], default='Sepi', max_length=255)),
                ('deskripsi', models.TextField(default=None)),
                ('alamat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Alamat')),
                ('penulisSurvey', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
